/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef raft_CONSTANTS_H
#define raft_CONSTANTS_H

#include "raft_types.h"



class raftConstants {
 public:
  raftConstants();

};

extern const raftConstants g_raft_constants;



#endif
